Update buildbot to 3.2.0
This patch does a number of things to update zfs-buildbot from
buildbot 0.8.x to 3.2.0.

- Remove old patchsets
- Use "worker" terminology to match new buildbot APIs.
- Make a bunch of previously hard-coded global variables optionally
  set-able in password.py (for testing only).
- Correctly name the coverage tester Ubuntu 17 instead of 18
- Add nginx config to README.md and Ubuntu 20.04 setup instructions
  for buildbot.
- Fix get_freebsd_image(): 'NoneType' object has no attribute 'get_image'
- Base64 encode user_data to get around error
- Update block_device_map
- Integrate isIdle() patch into zfs-buildbot.  We no longer have an
  idle worker state, so just check to see if a builder is available.
- Get rid of: "logHorizon/buildHorizon is deprecated" warnings
- Get rid of special chars in worker names (like '.').  This gets
  around an error:
       "worker name '<worker name>' is not an identifier
- Fix auth/authz/www stuff
- Fix 'nextWorker now takes a 3rd argument'
- Fix error while parsing config file: cannot import name 'html'
- mergeRequests -> collapseRequests
- Make boot_device_map a list to match new API
- Fix "builtins.TypeError: __init__() takes at least 3 arguments"
- buildbot.status.results -> buildbot.process.results
- Misc other updates
- Remove 'lazylogfiles' due to buildbot bug:
  https://github.com/buildbot/buildbot/issues/5957

Signed-off-by: Tony Hutter <hutter2@llnl.gov>